version: '3'
services:

  # we need this to work with DB version 11.2.0.4 !!!
  # does not seem to work with XE

  # docker-compose exec oracle tail -f /u01/app/oracle/diag/rdbms/ee/EE/trace/alert_EE.log
  # docker-compose exec oracle sqlplus system/oracle
  oracle:
    image: sath89/oracle-ee-11g

  # oracle:
  #   image: container-registry.oracle.com/database/enterprise:12.2.0.1-slim

  # docker-compose exec node bash
  # > npx ts-node ./index.ts
  node:
    # image: node:10
    # command: ["npm", "start"]
    # command: ["npm", "run", "loop"]
    command: sh -c "npm install && npm start"
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - oracle
